import 'package:powersync/powersync.dart';

/// Mirrors [db/init.sql] Postgres tables. PowerSync adds `id` automatically.
const Schema healthNotesSchema = Schema([
  Table('health_notes', [
    Column.text('user_id'),
    Column.text('date_time'),
    Column.text('symptoms_list'),
    Column.text('drug_doses'),
    Column.text('notes'),
    Column.text('applied_tools'),
    Column.text('created_at'),
    Column.text('updated_at'),
    Column.integer('is_deleted'),
  ]),
  Table('check_ins', [
    Column.text('user_id'),
    Column.text('metric_name'),
    Column.integer('rating'),
    Column.text('date_time'),
    Column.text('created_at'),
    Column.text('updated_at'),
    Column.integer('is_deleted'),
  ]),
  Table('user_profiles', [
    Column.text('email'),
    Column.text('full_name'),
    Column.text('avatar_url'),
    Column.text('updated_at'),
  ]),
  Table('check_in_metrics', [
    Column.text('user_id'),
    Column.text('name'),
    Column.text('type'),
    Column.integer('color_value'),
    Column.integer('icon_code_point'),
    Column.integer('sort_order'),
    Column.text('created_at'),
    Column.text('updated_at'),
    Column.integer('is_deleted'),
  ]),
  Table('conditions', [
    Column.text('user_id'),
    Column.text('name'),
    Column.text('start_date'),
    Column.text('end_date'),
    Column.text('condition_status'),
    Column.integer('color_value'),
    Column.integer('icon_code_point'),
    Column.text('notes'),
    Column.text('created_at'),
    Column.text('updated_at'),
    Column.integer('is_deleted'),
  ]),
  Table('condition_entries', [
    Column.text('condition_id'),
    Column.text('entry_date'),
    Column.integer('severity'),
    Column.text('phase'),
    Column.text('notes'),
    Column.text('linked_check_in_id'),
    Column.text('created_at'),
    Column.text('updated_at'),
    Column.integer('is_deleted'),
  ]),
  Table('medication_schedules', [
    Column.text('user_id'),
    Column.text('medication_name'),
    Column.text('unit'),
    Column.text('start_date'),
    Column.text('end_date'),
    Column.text('steps'),
    Column.text('notes'),
    Column.text('created_at'),
    Column.text('updated_at'),
    Column.integer('is_deleted'),
  ]),
  Table('health_tool_categories', [
    Column.text('name'),
    Column.text('description'),
    Column.text('icon_name'),
    Column.text('color_hex'),
    Column.integer('sort_order'),
    Column.integer('is_active'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('health_tools', [
    Column.text('name'),
    Column.text('description'),
    Column.text('category_id'),
    Column.integer('sort_order'),
    Column.integer('is_active'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
]);
